# .coderabbit.yaml

reviews:
  - name: Spec Alignment & Governance Review
    prompt: |
      You are reviewing code for Project Chimera, a strictly spec-driven autonomous influencer system using FastRender Swarm and MCP.
      First, thoroughly check the specs/ directory (_meta.md, functional.md, technical.md, openclaw_integration.md).
      Verify that any new or modified code:
      - Strictly adheres to API contracts, schemas, and constraints in specs/technical.md
      - Implements only ratified functional requirements from specs/functional.md
      - Respects core constraints in specs/_meta.md (MCP exclusive, no direct API calls, no premature implementation)
      Quote exact spec sections for any deviation.
      Reject any implementation code that appears before specs are complete or tests pass.

  - name: Security & Best Practices Review
    prompt: |
      Perform a comprehensive security scan with focus on:
      - Hardcoded secrets, keys, or credentials (especially Coinbase AgentKit/wallet related)
      - Unsafe external interactions (must route exclusively through MCP)
      - Injection risks, path traversal, or unsafe deserialization
      - Exposure of sensitive data (wallet addresses, private keys)
      Also enforce Python best practices: proper type hints, error handling, and avoidance of anti-patterns.
      Reference OWASP Top 10 or similar guidelines where applicable.